### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by Waxjjya** [SingleJohn/sehuatang#1]
请问python版本有没有要求呀，我在使用时遇到syntaxerror:'continue'not supported inside 'finally' clause，是否是python版本问题

**Comment by SingleJohn** [comment]
我调试用的的3.8版本，看看是不是有些库没装，然后分支用 async

**Comment by Waxjjya** [comment]
> 我用调试的3.8版本，看看不是什么库没装，然后用async分支

多谢
