### ISSUE TITLE
运行不起来，biu~的一下就退出了

### ISSUE THREAD

**Issue by xrbzy64** [SingleJohn/sehuatang#11]
依赖正常
root@23-9-232259:~# cd /root/sehuatang-2.0
root@23-9-232259:~/sehuatang-2.0# pip install -r requirements.txt
Requirement already satisfied: beautifulsoup4==4.10.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (4.10.0)
Requirement already satisfied: httpx==0.22.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (0.22.0)
Requirement already satisfied: pymongo==4.0.2 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 3)) (4.0.2)
Requirement already satisfied: PyYAML==6.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 4)) (6.0)
Requirement already satisfied: python-telegram-bot~=13.11 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 5)) (13.15)
Requirement already satisfied: bs4~=0.0.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 7)) (0.0.1)
Requirement already satisfied: requests~=2.27.1 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 8)) (2.27.1)
Requirement already satisfied: pymysql~=1.0.2 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 9)) (1.0.3)
Requirement already satisfied: schedule~=1.1.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 10)) (1.1.0)
Requirement already satisfied: pyTelegramBotAPI~=4.6.0 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 11)) (4.6.1)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.8/dist-packages (from beautifulsoup4==4.10.0->-r requirements.txt (line 1)) (2.5)
Requirement already satisfied: certifi in /usr/lib/python3/dist-packages (from httpx==0.22.0->-r requirements.txt (line 2)) (2019.11.28)
Requirement already satisfied: httpcore<0.15.0,>=0.14.5 in /usr/local/lib/python3.8/dist-packages (from httpx==0.22.0->-r requirements.txt (line 2)) (0.14.7)
Requirement already satisfied: charset-normalizer in /usr/local/lib/python3.8/dist-packages (from httpx==0.22.0->-r requirements.txt (line 2)) (3.3.0)
Requirement already satisfied: sniffio in /usr/local/lib/python3.8/dist-packages (from httpx==0.22.0->-r requirements.txt (line 2)) (1.3.0)
Requirement already satisfied: rfc3986[idna2008]<2,>=1.3 in /usr/local/lib/python3.8/dist-packages (from httpx==0.22.0->-r requirements.txt (line 2)) (1.5.0)
Requirement already satisfied: cachetools==4.2.2 in /usr/local/lib/python3.8/dist-packages (from python-telegram-bot~=13.11->-r requirements.txt (line 5)) (4.2.2)
Requirement already satisfied: tornado==6.1 in /usr/local/lib/python3.8/dist-packages (from python-telegram-bot~=13.11->-r requirements.txt (line 5)) (6.1)
Requirement already satisfied: APScheduler==3.6.3 in /usr/local/lib/python3.8/dist-packages (from python-telegram-bot~=13.11->-r requirements.txt (line 5)) (3.6.3)
Requirement already satisfied: pytz>=2018.6 in /usr/local/lib/python3.8/dist-packages (from python-telegram-bot~=13.11->-r requirements.txt (line 5)) (2023.3.post1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests~=2.27.1->-r requirements.txt (line 8)) (1.25.8)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /usr/lib/python3/dist-packages (from requests~=2.27.1->-r requirements.txt (line 8)) (2.8)
Requirement already satisfied: h11<0.13,>=0.11 in /usr/local/lib/python3.8/dist-packages (from httpcore<0.15.0,>=0.14.5->httpx==0.22.0->-r requirements.txt (line 2)) (0.12.0)
Requirement already satisfied: anyio==3.* in /usr/local/lib/python3.8/dist-packages (from httpcore<0.15.0,>=0.14.5->httpx==0.22.0->-r requirements.txt (line 2)) (3.7.1)
Requirement already satisfied: setuptools>=0.7 in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python-telegram-bot~=13.11->-r requirements.txt (line 5)) (45.2.0)
Requirement already satisfied: tzlocal>=1.2 in /usr/local/lib/python3.8/dist-packages (from APScheduler==3.6.3->python-telegram-bot~=13.11->-r requirements.txt (line 5)) (5.0.1)
Requirement already satisfied: six>=1.4.0 in /usr/lib/python3/dist-packages (from APScheduler==3.6.3->python-telegram-bot~=13.11->-r requirements.txt (line 5)) (1.14.0)
Requirement already satisfied: exceptiongroup; python_version < "3.11" in /usr/local/lib/python3.8/dist-packages (from anyio==3.*->httpcore<0.15.0,>=0.14.5->httpx==0.22.0->-r requirements.txt (line 2)) (1.1.3)
Requirement already satisfied: backports.zoneinfo; python_version < "3.9" in /usr/local/lib/python3.8/dist-packages (from tzlocal>=1.2->APScheduler==3.6.3->python-telegram-bot~=13.11->-r requirements.txt (line 5)) (0.2.1)

运行闪退 
![image](https://github.com/SingleJohn/sehuatang/assets/146699662/419253ae-cde5-4839-aba8-2de7c11024ca)

![image](https://github.com/SingleJohn/sehuatang/assets/146699662/5f2b6195-80d4-467e-a0ef-b216b6f45c71)

下面是我的config

![image](https://github.com/SingleJohn/sehuatang/assets/146699662/6dc6db85-5789-4f3f-9a62-9759c66e5638)

大佬看下是什么原因，谢谢谢谢！

**Comment by xrbzy64** [comment]
大佬你好，我加了cookie和更改了免翻地址，还是一样的错误。

我知道您的公共库很齐全，其实我主要是想爬取去年5月（也就是项目）之前的磁力...公共库没有。

**Comment by SingleJohn** [comment]
看日志已经正常运行了，应该是解析部分的问题，加了cookie没有用，手动打断点看看请求到的内容吧😄

**Comment by hjl0528** [comment]
> 大佬你好，我加了cookie和更改了免翻地址，还是一样的错误。
> 
> 我知道您的公共库很齐全，其实我主要是想爬取去年5月（也就是项目）之前的磁力...公共库没有。

cookie在代码里没有调用 ，两个请求的方法加一下就可以了
![Snipaste_2023-10-16_22-04-41](https://github.com/SingleJohn/sehuatang/assets/82209445/1c6c769b-8c1a-4387-ba45-7b08cb27f2cd)

**Comment by xrbzy64** [comment]
![image](https://github.com/SingleJohn/sehuatang/assets/146699662/551a3d80-4803-4022-a4f6-95c2428a223a)
感谢回复，抱歉，我才看到。。。我的跟你的不一样，是直接按照你这个修改吗？谢谢。
