### ISSUE TITLE
使用体验很爽，感谢！3个问题：1.怎么让拖动时减少卡顿 2.可否添加fc2视频

### ISSUE THREAD

**Issue by ydwg** [SingleJohn/sehuatang#15]
频繁拖动时候会卡，有什么好方法吗？（常用视频软件那种暂停就自动缓存的方法，emby无效）

3.联通用哪个地区的梯子效果好呢？韩国/日本/港台？
如上，再次感谢大佬！

**Comment by SingleJohn** [comment]
![image](https://github.com/SingleJohn/sehuatang/assets/102285475/48c53f5d-dfa6-48d2-af95-d135de944379)

服务器地址在韩国，理论上韩国代理会好一些

实际播放的时候会从网盘下载到服务器，再推流，emby客户端就算暂停，默认也只会缓存一点点，可以设置外部播放器PotPlayer，会一直缓存后面的内容
