### ISSUE TITLE
求新开频道

### ISSUE THREAD

**Issue by lezaijjh** [SingleJohn/sehuatang#24]
早上突然发现被封了，十分难受，已经连续看一年了，希望大牛能新开频道

**Comment by lezaijjh** [comment]
真的好难受，每天早上起床就是来看频道

**Comment by SingleJohn** [comment]
被举报封的，账号也封了
看数据库吧，或者自己建一个私有频道，自己推

**Comment by lezaijjh** [comment]
> 被举报封的，账号也封了 看数据库吧，或者自己建一个私有频道，自己推

辛苦了！不知道之前频道的bot能否开源，技术能力实在有限😭

**Comment by zyd16888** [comment]
> > 被举报封的，账号也封了 看数据库吧，或者自己建一个私有频道，自己推
> 
> 辛苦了！不知道之前频道的bot能否开源，技术能力实在有限😭

https://github.com/SingleJohn/sehuatang/blob/v2/util/sendTelegram.py

这个，换个分支就能看到所有代码了

**Comment by SingleJohn** [comment]
> > 被举报封的，账号也封了 看数据库吧，或者自己建一个私有频道，自己推
> 
> 辛苦了！不知道之前频道的bot能否开源，技术能力实在有限😭

https://github.com/SingleJohn/sehuatang/blob/v2/util/sendTelegram.py
这个，换个分支就能看到所有代码了
