### ISSUE TITLE
请问一下 报如下错误

### ISSUE THREAD

**Issue by Hazard804** [SingleJohn/sehuatang#4]
![image](https://user-images.githubusercontent.com/82299110/184670631-1d9c63d4-e139-4587-bd8f-bd15a7fadf1f.png)
环境win11 python3.8 配置文件如下
![image](https://user-images.githubusercontent.com/82299110/184670787-069e6286-4d6b-40ef-a416-a8024ba30cd0.png)

**Comment by SingleJohn** [comment]
telegram 的token有问题，代码的问题，在false的时候只是不发消息，bot还是初始化了

**Comment by SingleJohn** [comment]
刚改了一下，已经处理好了，直接clone v2分支，用最新版吧，有问题再反馈哈，注意v2分支的配置文件fid部分有变化

**Comment by Hazard804** [comment]
了解 晚点尝试一下 感谢大佬回复

**Comment by Hazard804** [comment]
使用v2版本出现如下错误
![image](https://user-images.githubusercontent.com/82299110/184801217-fa668947-64c8-48ff-969f-0ecfe65178be.png)
![image](https://user-images.githubusercontent.com/82299110/184801239-6d6fce10-82d3-49f7-b54a-93fb4d8c5afd.png)

**Comment by SingleJohn** [comment]
httpx.ConnectError 说明请求出问题了，查下网络或者代理吧

**Comment by Hazard804** [comment]
![image](https://user-images.githubusercontent.com/82299110/185032096-bd3a4faa-cfae-42cb-a947-9b2f78b8b633.png)
我是使用clash代理 端口是7890 每次运行之后clash日志会显示 但是过几秒就断开
![image](https://user-images.githubusercontent.com/82299110/185032896-65a722b7-bfbc-4c24-ba30-f66292bbea43.png)
我自己手动访问是正常访问的
![image](https://user-images.githubusercontent.com/82299110/185032966-73d88c3d-1448-4323-9872-fb8b3ce24a27.png)

**Comment by SingleJohn** [comment]
我本地用的也是clash，没有办法复现问题，我看你的截图是python3.10版本，刚刚特意用3.10版本试了下，也没问题
我贴一下我的操作截图、配置和日志吧，再不行，那就没辙了
![image](https://user-images.githubusercontent.com/102285475/185041844-91755415-0379-4845-bc33-b39b23ab7089.png)
![image](https://user-images.githubusercontent.com/102285475/185041887-ff03cab7-0243-45d5-b695-0682288f0e62.png)
![image](https://user-images.githubusercontent.com/102285475/185041933-5587a517-5e27-4d53-93da-5062eaf0fe42.png)
![image](https://user-images.githubusercontent.com/102285475/185042086-5af969a6-4244-47b4-8912-4b407ad5db05.png)

**Comment by Hazard804** [comment]
好的 感谢大佬

**Comment by Hazard804** [comment]
问题已解决 猜测是由于使用的机场线路有其他人触发了sehua的限制 封ip了 换一个机场就好了
