### ISSUE TITLE
docker-compose 启动后没反应？

### ISSUE THREAD

**Issue by vvlaw** [SingleJohn/sehuatang#5]
git clone 代码后，修改配置文件，运行 docker-compose up -d 启动服务
docker-compose.yml文件默认包含了mongodb和mysql服务，自行按需修改
config_docker.yaml 为docker运行示例配置文件

请问config_docker和docker-compose.yml里面的配置改如何修改呢？我在config_docker.yaml里面加了token后，bot发指令没反应。

**Comment by SingleJohn** [comment]
感谢反馈，bot属于v2版功能，并没有在docker里面提供，预计近期有空的话（主业太忙了）会更新一版新的，到时候会考虑
