### ISSUE TITLE
无法连接公共 mongodb 库

### ISSUE THREAD

**Issue by AAlexDing** [SingleJohn/sehuatang#6]
2023-03-01T09:34:10.504+0000 W NETWORK  [js] Unable to reach primary for set atlas-lkohbc-shard-0
*** It looks like this is a MongoDB Atlas cluster. Please ensure that your IP whitelist allows connections from your network.

gcp和本地访问都不行

**Comment by SingleJohn** [comment]
入站ip都是放开的，没有限制
<img width="1088" alt="1677847663801" src="https://user-images.githubusercontent.com/102285475/222724136-e6b0ba55-d237-4589-8ec7-e9fc0f882c98.png">
使用的keh客户端是datagrip
<img width="465" alt="image" src="https://user-images.githubusercontent.com/102285475/222724677-b4d3f376-ea4e-44bb-a50d-e19285036e62.png">
<img width="437" alt="image" src="https://user-images.githubusercontent.com/102285475/222724850-65ace0de-6bde-4d40-ae22-e2d023769231.png">
用了多个ip测试，都是可以的
<img width="870" alt="image" src="https://user-images.githubusercontent.com/102285475/222724980-bc206007-4a46-49c9-93b1-05c8a3018903.png">
<img width="896" alt="1677848266009" src="https://user-images.githubusercontent.com/102285475/222725988-b4bec667-bf12-4169-911d-a4e9910f9fc3.png">
